export const en = {
  app_name: "Demiurge Assistant",
  nav_chat: "AI Chat",
  nav_wiki: "Wiki",
  nav_timeline: "Timeline",
  nav_map: "World Map",
  nav_tables: "Random Tables",
  nav_journal: "Journal",
  nav_quests: "Quests",
  nav_settings: "Settings",
  loading: "Loading...",
  
  settings_title: "Settings",
  settings_universe_settings: "Universe Settings",
  settings_current_universe: "Current Universe",
  settings_select_universe: "-- Select Universe --",
  settings_new_universe_name: "New Universe Name",
  settings_create: "Create",
  settings_generate_demo: "Generate Demo Universe (Sci-Fi)",
  settings_app_settings: "App Settings",
  settings_ai_text: "Text AI (Chat, Journal)",
  settings_ai_image: "Image Generation",
  settings_provider: "Provider",
  settings_provider_openai: "OpenAI-Compatible (LM Studio, ChatGPT, DeepSeek, Qwen)",
  settings_provider_gemini: "Google Gemini",
  settings_provider_sd: "Stable Diffusion (Automatic1111)",
  settings_provider_dalle: "OpenAI DALL-E",
  settings_api_key: "API Key (if required)",
  settings_image_endpoint: "Image Server URL (e.g. http://127.0.0.1:7860)",
  settings_llm_endpoint: "LLM Endpoint URL (e.g. http://localhost:1234/v1)",
  settings_llm_model: "Model Name",
  settings_language: "Language",
  settings_save: "Save",
  settings_saved: "Settings saved",
  
  settings_help_title: "Help: Running locally and connecting to LM Studio",
  settings_help_intro: "To run the application completely autonomously and for free, you can run it on your computer and connect to a local language model via LM Studio.",
  settings_help_step1_title: "Step 1: Running the app locally",
  settings_help_step1_1: "Download the project source code (Export -> Download ZIP) and extract it to a convenient folder.",
  settings_help_step1_2: "Navigate to the extracted folder.",
  settings_help_step1_3: "For Windows: Double-click the start.bat file. The script will download portable Node.js (if needed), install dependencies, and start the server.",
  settings_help_step1_4: "For macOS/Linux: Open a terminal in this folder and run bash start.sh.",
  settings_help_step1_5: "The browser with the app will open automatically!",
  settings_help_step1_6: "",
  settings_help_step2_title: "Step 2: Configuring LM Studio",
  settings_help_step2_1: "Download and install LM Studio from the official website (lmstudio.ai).",
  settings_help_step2_2: "Open LM Studio and download any suitable model (e.g., Llama 3, Mistral, or Qwen).",
  settings_help_step2_3: "Go to the Local Server tab (server icon on the left).",
  settings_help_step2_4: "Select the downloaded model at the top.",
  settings_help_step2_5: "Ensure the port is set to 1234 (default).",
  settings_help_step2_6: "Enable the CORS (Cross-Origin Resource Sharing) option so the app can send requests to the server.",
  settings_help_step2_7: "Click the Start Server button.",
  settings_help_step3_title: "Step 3: Connecting in the app",
  settings_help_step3_1: "Return to this settings menu in the app.",
  settings_help_step3_2: "In the LLM Endpoint field, enter: http://localhost:1234/v1",
  settings_help_step3_3: "In the LLM Model field, enter: local-model (or the exact model name from LM Studio).",
  settings_help_step3_4: "Click Save Settings.",
  settings_help_step3_5: "Now you can use the AI chat and content generation completely for free and privately!",
  
  // Export/Import
  settings_export_import_title: "Export and Import",
  settings_export_btn: "Export World",
  settings_import_btn: "Import World",
  settings_export_import_desc: "Export will save all your universes, entities, maps, and settings into a single JSON file. Import will completely overwrite current data.",
  settings_import_warning: "Warning! Import will completely overwrite all current data. Continue?",
  settings_import_success: "Import completed successfully! The application will reload.",
  settings_import_error: "Import Error",
  settings_export_error: "Export Error",

  chat_placeholder: "Describe your idea, location, or character...",
  chat_send: "Send",
  
  wiki_title: "Wiki",
  wiki_search: "Search...",
  wiki_type_npc: "NPCs",
  wiki_type_enemy: "Enemies",
  wiki_type_item: "Items",
  wiki_type_location: "Locations",
  wiki_type_country: "Countries",
  wiki_type_faction: "Factions",
  wiki_type_settlement: "Settlements",
  wiki_type_pc: "Player Characters",
  wiki_all_types: "All Types",
  wiki_all_tags: "All Tags",
  wiki_add_new: "Add New",
  wiki_back: "Back to Wiki",
  wiki_entity_name: "Entity Name",
  wiki_image_url: "Image URL or upload...",
  wiki_generate_image: "Generate AI Portrait",
  wiki_generating: "Generating...",
  wiki_upload_image: "Upload Image",
  wiki_description: "Detailed description... Use [[Entity Name]] to link to other pages.",
  wiki_tags: "Tags (comma separated)",
  wiki_delete: "Delete",
  wiki_cancel: "Cancel",
  wiki_save: "Save",
  wiki_no_description: "No description provided.",
  wiki_no_entities: "No entities found.",
  wiki_delete_confirm: "Are you sure you want to delete this entity?",
  wiki_upload_failed: "Failed to upload image",
  wiki_list_view: "List View",
  wiki_graph_view: "Graph View",
  wiki_graph_help: "Scroll to zoom, drag to pan. Click nodes to open.",
  wiki_backlinks: "Linked Mentions",
  wiki_backlinks_empty: "No linked mentions found.",
  
  map_title: "World Map",
  map_level_galaxy: "Galaxy",
  map_level_system: "Star System",
  map_level_planet: "Planet",
  map_level_hex: "Hex",
  map_regenerate_confirm: "Are you sure you want to regenerate the grid? All existing hexes and their data will be lost.",
  map_new: "New",
  map_unknown: "unknown",
  map_back: "Back",
  map_edit_mode: "Edit Mode",
  map_place_node: "Place Node",
  map_generate_grid: "Generate Grid",
  map_regenerate_grid: "Regenerate Grid",
  map_biome_random: "Random Biome",
  map_biome_forest: "Forest",
  map_biome_desert: "Desert",
  map_biome_water: "Water",
  map_biome_mountain: "Mountain",
  map_biome_plains: "Plains",
  map_biome_winter: "Winter",
  map_biome_stone: "Stone",
  map_appearance: "Appearance",
  map_color: "Color",
  map_image_url: "Image URL",
  map_size: "Size",
  map_properties: "Properties",
  map_select_node: "Select a node on the map to view details",
  map_click_to_place: "Click map to place",
  map_add: "Add",
  map_done_editing: "Done Editing",
  map_edit_map: "Edit Map",
  map_universe_map: "Universe Map",
  map_map: "Map",
  map_name: "Name",
  map_description: "Description",
  map_delete_node: "Delete Node",
  map_save: "Save",
  map_drag_hint: "You can also drag nodes on the map to move them.",
  map_no_description: "No description available.",
  map_enter: "Enter",
  map_open_wiki: "Open in Wiki",

  // Timeline
  timeline_title: "Timeline",
  timeline_add_event: "Add Event",
  timeline_back: "Back to Timeline",
  timeline_event_title: "Event Title",
  timeline_date: "Date (e.g., 1482 DR)",
  timeline_description: "Detailed description...",
  timeline_order_index: "Order Index:",
  timeline_delete: "Delete",
  timeline_cancel: "Cancel",
  timeline_save: "Save",
  timeline_no_description: "No description provided.",
  timeline_no_events: "No events found.",
  timeline_delete_confirm: "Are you sure you want to delete this event?",

  tables_title: "Random Tables",
  tables_search: "Search tables...",
  tables_filter_all: "All Types",
  tables_add: "Add Table",
  tables_name: "Table Name",
  tables_type_general: "General",
  tables_type_weather: "Weather",
  tables_type_event: "Event",
  tables_type_loot: "Loot",
  tables_type_encounter: "Encounter",
  tables_roll_weight: "By Weight",
  tables_roll_dice: "D&D (1 to N)",
  tables_description: "Description",
  tables_conditions: "Conditions",
  tables_add_condition: "Add Condition",
  tables_cond_location: "Location",
  tables_cond_politics: "Politics",
  tables_cond_environment: "Environment",
  tables_cond_biome: "Biome",
  tables_cond_value: "Value (e.g. 'Forest', 'Hostile')",
  tables_no_conditions: "No conditions set. Table applies everywhere.",
  tables_entries: "Entries",
  tables_add_entry: "Add Entry",
  tables_weight: "Weight",
  tables_result: "Result text...",
  tables_cancel: "Cancel",
  tables_save: "Save Table",
  tables_roll_col: "Roll",
  tables_result_col: "Result",

  // Markdown Editor
  md_edit: "Edit",
  md_preview: "Preview",
  md_help: "Markdown is supported (**, *, #, -, 1., [link](url))",

  // Journal
  journal_title: "Campaign Journal",
  journal_placeholder: "Describe what happened during the session... (e.g., The heroes arrived in Rivendell and met Elrond. They learned about the ring and decided to go to Mordor.)",
  journal_analyze: "Analyze with AI",
  journal_analyzing: "Analyzing...",
  journal_results_title: "Extracted Data",
  journal_no_results: "AI didn't find any new entities or events. Try to describe in more detail.",
  journal_entities_found: "Found Entities",
  journal_events_found: "Found Events",
  journal_save_selected: "Save Selected",
  journal_saved_success: "Data successfully saved to Wiki and Timeline!",
  journal_error: "Error during analysis. Check AI settings.",
  journal_new_log: "New Entry",
  journal_title_placeholder: "Session title...",
  journal_date: "Session Date",
  journal_save_log: "Save Entry",
  journal_logs_list: "Session History",
  journal_empty: "Journal is empty. Add your first entry!",
  journal_back: "Back to list",
  journal_delete_confirm: "Delete this entry?",

  // Quests
  quests_title: "Quest Board",
  quests_add: "Add Quest",
  quests_todo: "Hooks",
  quests_in_progress: "Active",
  quests_done: "Done",
  quests_failed: "Failed",
  quests_new_title: "New Quest",
  quests_delete_confirm: "Delete quest?",

  // Boards
  boards_title: "Detective Boards",
  boards_create: "Create Board",
  boards_new_name: "New Board",
  boards_back: "Back",
  boards_save: "Save",
  boards_add_note: "Add Note",
  boards_delete_confirm: "Delete this board?",
  boards_empty: "No boards yet. Create one to start investigating!",

  // Help
  help_title: "Help & Guide",
  help_markdown: "Markdown Cheat Sheet",
  help_sections: "App Sections",
  help_player_mode: "Player Mode & Secret Elements",
};
