{
  "name": "react-example",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "tsx server.ts",
    "build": "vite build && esbuild server.ts --bundle --platform=node --format=cjs --packages=external --sourcemap --outfile=dist/server.cjs",
    "preview": "vite preview",
    "clean": "rm -rf dist",
    "lint": "tsc --noEmit",
    "start": "node dist/server.cjs",
    "test": "vitest run"
  },
  "dependencies": {
    "@google/genai": "^1.50.0",
    "@tailwindcss/typography": "^0.5.19",
    "@tailwindcss/vite": "^4.1.14",
    "@vitejs/plugin-react": "^5.0.4",
    "@xyflow/react": "^12.10.2",
    "better-sqlite3": "^12.4.1",
    "d3": "^7.9.0",
    "dotenv": "^17.2.3",
    "express": "^4.21.2",
    "jsonrepair": "^3.14.0",
    "lucide-react": "^0.546.0",
    "motion": "^12.23.24",
    "multer": "^2.1.1",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-markdown": "^10.1.0",
    "remark-gfm": "^4.0.1",
    "textarea-caret": "^3.1.0",
    "vite": "^6.2.0"
  },
  "devDependencies": {
    "@types/d3": "^7.4.3",
    "@types/express": "^4.17.21",
    "@types/multer": "^2.1.0",
    "@types/node": "^22.14.0",
    "autoprefixer": "^10.4.21",
    "esbuild": "^0.28.0",
    "tailwindcss": "^4.1.14",
    "tsx": "^4.22.1",
    "typescript": "~5.8.2",
    "vite": "^6.2.0",
    "vite-node": "^5.3.0",
    "vitest": "^4.1.6"
  }
}
